hrkfdn/ncspot

README.md
src/main.rs
src/spotify.rs
src/ui/mod.rs
src/ui/playlist.rs

This is a fairly crude implementation of playlists.
It pulls the users playlist on boot and then displays them when hitting F4.
Pressing `return` on a playlist queues the songs.
Stuff that could be cool for either this PR or followups:
* only load the playlist when actually jumping to the view
* allow refreshing the playlists
* disconnect playing of a playlist from the queue and allow to repeat songs etc.

Implement basic playlist that simply queues songs

---

README.md

tried installing on Mac and pkg-config needed to be separately installed

add pkg-config as a requirement

---

src/events.rs
src/main.rs
src/spotify.rs
src/ui/layout.rs
src/ui/mod.rs
src/ui/queue.rs
src/ui/search.rs
src/ui/statusbar.rs

I added a status bar containing playback status, name and duration with a progress bar spanning the entire line above. I'm not sure yet whether that's a good use of space, or if that should be integrated into the single line (this might look odd because of being off-center). It could potentially automatically be removed if the window height drops below a certain treshold.
To accomplish this, I also made some other changes:
- Wrapping all main views inside a custom layout for view switching
- Changing the load command to use `FullTrack` instead of `SpotifyId`
- Keeping track of the currently playing track in `Spotify`
- Renaming `PlayerState` to `PlayerStatus` to prevent misunderstandings, since the state of the entire player consists of that status, the current track and other data.
- …

Add main layout view and status bar

---

src/commands.rs
src/events.rs
src/main.rs
src/ui/layout.rs

As promised, adds a basic vim-style command line. I replaced all the existing (global) keybindings with commands. This allows easy rebinding, although at the moment they remain hardcoded.
Command callbacks return `Result<Option<String>, String>`. If an error is returned, the text is displayed above the command line.
The `:search` command allows entering the query directly, although the `on_submit` callback is currently not called, so you still have to press Enter.

Add a vim-style command line

---

src/main.rs

I tend to use ncspot in whatever project directory I'm currently in, so I have a bunch of these 'ncspot.log' files hanging around now. Turning this off, but leaving the structure there so it can be a command line option later

turn off writing log to file

---

Cargo.toml
src/main.rs
src/mpris.rs
src/queue.rs
src/track.rs

Implements a D-Bus server responding to the `org.mpris.MediaPlayer2` and `org.mpris.MediaPlayer2.Player` specifications as an optional feature:
https://specifications.freedesktop.org/mpris-spec/latest/
`org.mpris.MediaPlayer2.TrackList` and `org.mpris.MediaPlayer2.Playlists` are not implemented, but this is enough to read metadata and control playback.
This should satisfy #9 on D-Bus systems at least.

Implement MPRIS D-Bus spec

---

Cargo.toml
src/main.rs
src/mpris.rs

Refactored the DBus server, yanking out all the `dbus-tokio` stuff since it failed in interesting and annoying ways when I tried to implement a manual poll loop and manually sending out `PropertiesChanged` signals when needed.
I also fixed a typo in the interface name and the artists being strings instead of arrays (this caused an error in the GNOME shell on top of the missing events).

Refactor DBus server, implement PropertiesChanged

---

src/commands.rs
src/ui/listview.rs
src/ui/playlists.rs
src/ui/queue.rs
src/ui/search.rs

Implements a scroll bar in `ListView` directly, without having to rely on `ScrollView`. Makes things cleaner in the main views, and stops `ScrollView` from consuming arrow key events, making those rebindable.

Add scroll bar to ListView, remove ScrollView

---

README.md

It took me a little while to figure out it was `libdbus-1-dev` so noting it in the README

Include new build requirement

---

Cargo.toml
src/commands.rs
src/config.rs
src/main.rs
src/mpris.rs
src/queue.rs
src/spotify.rs
src/track.rs
src/ui/layout.rs
src/ui/statusbar.rs

Adds seeking (both with commands/keys and mouse events in the progress bar), shuffle and repeat. All in one PR mostly because I wanted seeking to test it. Let me know if you want me to split these up into multiple PRs.
Since there are no proper Unicode characters for repeat/shuffle, I added a config setting to use NerdFont characters for shuffle, repeat and playback status:
I also reintroduced the PulseAudio backend since Rodio didn't work on my system (other people with similar setups seem to have issues as well: https://github.com/tomaka/rodio/issues/173). I was working on a build script to set a sensible backend at compile time, but I still have some kinks to work out there.

Add seeking, shuffle and repeat

---

src/commands.rs
src/main.rs
src/playlists.rs
src/track.rs
src/traits.rs
src/ui/layout.rs
src/ui/listview.rs
src/ui/playlists.rs
src/ui/queue.rs
src/ui/search.rs

I refactored the command handling to use a system similar to Cursive's event handling. Commands are sent to views recursively via a new trait before they are handled globally. This implements the original search bar focus behaviour with rebindable keys and makes command handling for currently selected items a bit easier. The default play/queue behaviour is implemented by `ListView` and can be prevented if necessary (e.g. in `QueueView`). This should scale better for more types (artists, albums) and list views.
I also changed the main focus keybindings (F1, F2, F3) to use a seperate `focus` command to avoid unnecessarily polluting the command namespace, so the "x selected" stuff isn't necessary anymore.

Refactor command handling

---

src/main.rs

This PR sets the file mode bits to 600 for credentials.toml. 
The `from_mode` (https://doc.rust-lang.org/std/os/unix/fs/trait.PermissionsExt.html#tymethod.from_mode) function is only available on Unix systems and since I don't have access to a Windows box I decided to set the target_family to unix.
Thanks for an awesome project!

Only allow owner read/write to credentials.toml

---

Cargo.toml
README.md

ncspot consumes ~40 % cpu when I use the rodio backend, when I switch to alsa it uses ~0-1% cpu instead.
The ncspot thread that is responsible for the 40 % cpu usage is the audio backend (playback) thread.
With rodio it consumes 40 % even though a song is not playing, but with alsa it just consumes the 40 % cpu during playback. So I prefer to compile it using the alsa backend so my cpu can rest a little when I'm not listening to anything :-)
This occurs on my Carbon X1 6th gen laptop with a Linux 4.15.0-47-generic kernel.

Add ALSA backend and fix typo in README.md

---

Cargo.toml
src/commands.rs
src/library.rs
src/main.rs
src/playlist.rs
src/spotify.rs
src/ui/listview.rs
src/ui/playlist.rs
src/ui/search.rs
src/ui/statusbar.rs

- Moved some of the playlist stuff out of library.rs to reduce that file in size a bit and bring playlists in line with all the other models.
- Displaying the following indicator only for playlists the user didn't create himself (#56).
- Prevented the `s` key from immediately deleting created playlists.
- Changed playlists to lazy-loading to avoid huge search delays (#62), the tracks are loaded when playing, saving or opening. It's probably unnecessary to download tracks for all search results since the user will in most cases not play any of them, or one/two at most.
- Displaying the saved indicator in the statusbar for the current track.
- Changed the `previous` command's behaviour to rewind to the start unless within the first 5 seconds of the track.
- Made the `play` command clear the …

Various Changes

---

README.md

As discussed in #84, this is just to document the list of packages one needs to install in Debian based systems for libxcb-*.

Add debian packages for libxcb development headers.

---

README.md

When I tried to compile ncspot on my machine (without python installed) it couldn't run the rust-xcb build script. This is because the rust-xcb build script is written in python 3, see: https://github.com/rtbo/rust-xcb/blob/master/rs_client.py.
I have added the python 3 requirement to the readme.

Add python3 dependency for building rust-xcb

---

README.md
src/commands.rs

Since you compare your app to 'mpd', I thought it would make sense to align the keybindings for the seek command with ncmpcpp, which is probably the most common mpd client:
- 'f' to seek forward
- 'b' to seek backward
I also implemented a fast-seek option, which would fix #104

Changed 'seek' keybinding to match ncmpcpp and added fast-seek

---

README.md

Hello! I added ncspot to the snap store - see https://snapcraft.io/ncspot - which has automated builds for i386, amd64, arm64, ppc64el and s390x (know anyone with an IBM mainframe who wants to listen to Spotify on it? :D )
This merge simply adds the build status as you have for repology. Sorry it doesn't line up. I'll start a conversation with repology to see if they can support snapcraft too. 
Thanks for making a great spotify client <3

Add snap build info

---

src/album.rs
src/artist.rs
src/playlist.rs
src/queue.rs
src/track.rs
src/ui/listview.rs
src/ui/queue.rs

Starting a playlist, album or artist with shuffle enabled always
starts on the first track in it and then plays the rest of the
queue shuffled.
This changes it so unless a track is picked directly, playback
will start on a random track of the selection.
This matches the behavior of most music players that I am aware of,
as well as the official Spotify client.

Shuffle: Start with a random track if not selecting track directly

---

src/spotify.rs

This one's a small change that doesn't really affect functionality and just gets rid of a warning during building, but ¯\_(ツ)_/¯
Buillding the program was successful on my end.

removed unnecessary parentheses

---

src/config.rs
src/main.rs
src/queue.rs
src/spotify.rs

I was a bit annoyed, that by default ncspot starts with shuffle and repeat turned off and volume at 100% so I thought why not change that.
This change lets ncspot read these options from the config.toml:
```
[saved_state]
volume = 0 - 65535
repeat = "track" | "playlist" | anything else defaults to no
shuffle = true | false
```
Those values are read at the start of the program and set the initial values of the respective variables.
Anyways, I love the app and I'm happy to contribute!
In the future I might write something to sync changes to these values made in the app with what's in the config file
PS: My first time writing in rust. Hope it's okayish code. There were many confusing hurdles for me as a newbie.

Added configuration option for initial shuffle, repeat, volume

---

README.md

Documents the feature introduced by #127 for configuring the initial state (for volume, repeat and shuffle) in the README.

README: Added doc for initial / save state

---

src/mpris.rs
src/spotify.rs

I have been working on a music bot project, and recently I found the ncspot project and wanted to add support to play Spotify songs via ncspot, because the regular Spotify client eats up so much RAM, the bot doesn't always work properly on low-end machines.
All was good until I finished implementing the new functionality and then I noticed that even though ncspot supports most of the mpris protocol, OpenUri method call was missing, which is one of the most important ones for my bot.
I then took a crash course in Rust and implemented it myself. You might want to review my code since I have never done Rust until now...

Added OpenUri D-BUS MPRIS support.

---

src/command.rs

This pull request allows the help keybinding to be configured to a different key in a user's configuration.
```toml
[keybindings]
"z" = "help"
```

[feat] add Command::Help to command.parse

---

src/command.rs
src/commands.rs

This pull request introduces a Noop command allowing the user to override default keybindings.
In the configuration a user can override a keybinding in the following way:
```toml
[keybindings]
"s" = "noop" # Disable default save keybinding
"d" = "noop" # Disable default delete keybinding
```

[feat] add Command::Noop

---

Cargo.lock
Cargo.toml
README.md
src/config.rs
src/main.rs
src/queue.rs
src/spotify.rs

Add desktop notification on playing new track

---

README.md
src/config.rs
src/spotify.rs

Added a config option `bitrate` that allows the bitrate to be set to 96, 160 or 320.
Implements #269

Added config option for bitrate

---

src/ui/tabview.rs

Condition to check if the tab is the last one was never met. Because of that the last tab wasn't well aligned when terminal width wasn't divisible by the number of tabs.

Fix last tab to fill entire width correctly

---

src/album.rs
src/artist.rs
src/commands.rs
src/episode.rs
src/playable.rs
src/playlist.rs
src/show.rs
src/track.rs
src/traits.rs
src/ui/listview.rs

Adds information about the album in a separate column, here's a picture for example:
This also appears in the queue.
Comes to implement #267

Display album name for playable objects 

---

src/queue.rs
src/ui/queue.rs

- When deleting the last song, update the ui focus (the actual cause for #253).
- Play next song when deleting the currently playing song from queue.
- When skipping to next song the `RepeatTrack` turns into a `RepeatPlaylist`.
- You can now play the expected previous track when shuffle is turned on .

Better queue behavior 

---

README.md
src/command.rs
src/commands.rs
src/main.rs
src/ui/layout.rs
src/ui/listview.rs

To start searching (only from `display_left`) just press `/` and begin typing the query.
`p` - go to currently playing
`.` - play next
`n` - search next
`N` - search previous
`esc` - close command line
Those are the keybindings I use on my fork, I guess you'd want to change some of them.

Vim like search

---

Cargo.lock
Cargo.toml
src/command.rs
src/commands.rs
src/main.rs
src/ui/listview.rs

- adds `:insert <url>` command to paste open.spotify.com links in ncspot
- use Ctrl-v or use :insert without an argument to paste from clipboard
- both open the selected item either in a modal or in a view (like when using "open current/selected")

feat: add insert command to paste spotify links

---

Cargo.lock
Cargo.toml
src/config.rs
src/main.rs

The `directories` create is no longer maintained.
Also it uses `~/Library/Preferences` on MacOS (https://github.com/dirs-dev/directories-rs/issues/62), but Apple advises against [creating files in `Preferences` sufolder](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1):
>This directory contains app-specific preference files. You should not create files in this directory yourself. Instead, use the NSUserDefaults class or CFPreferences API to get and set preference values for your app.In iOS, the contents of this directory are backed up by iTunes and iCloud.
[`platform-dirs`](https://github.com/cjbassi/platform-dirs-rs) allows to use `~/.config` on …

Replace "directories" crate with "platform_dirs"

---

src/mpris.rs

Seems that one of commit from #252 was lost so trying to do something with MPRIS via `playerctl` crashes because there's wrong `mpris:trackid` in the code.

Change to correct trackid

---

README.md
src/command.rs
src/playlist.rs
src/ui/listview.rs
src/ui/playlist.rs

This PR adds support for sorting tracks in a playlist, the function for sorting is generic but the command is only valid for playlists for now.
#189

Add support for sorting playlist tracks

---

src/library.rs
src/playlist.rs
src/ui/contextmenu.rs

Currently all playlists are showed when trying to add a track, this fixes so only playlists where the user is allowed to add tracks are shown.

Only show playlists where the user is allowed to add tracks when trying to add tracks

---

Cargo.toml
src/main.rs
src/sharing.rs
src/ui/contextmenu.rs
src/ui/listview.rs

Adds a feature flag to use the primary selection instead of the clipboard. Only works on Linux.

Allow primary selection for sharing

---

src/ui/layout.rs
src/ui/tabview.rs

Before this patch, we couldn't scroll ListViews contained by TabView with mouse.
This is because the default implementation of `cursive::traits::View::on_event` ignores any event.
This PR fixes the problem by forwarding events properly.

Enable mouse scrolling in TabViews

---

src/spotify.rs

Previously the country was not set at all. This had the behaviour that when country was required it was defaulted to the US, and when not required it would get all entries ignoring your current market. This had some weird implications especially when looking at an artists albums
After setting the correct country the list now looks like what I see in the desktop client:

Fix not setting correct country/market

---

src/ui/listview.rs

Before this fix, when adding duplicates to the queue, all duplicates would be shown as playing:
After, only the currently playing track is shown as playing.

Fix multiple tracks in queue being shown as playing

---

src/ui/layout.rs

With the changes that came from separating the search and search results in commit 18dc6c6 searches now opens a new view with the search results.
If you navigate a bit through the search results and navigate to albums and artists it takes multiple keypresses to return to the search view.
My solution is if you're viewing the search results and press to focus the search view again, the search results are closed and you're returned to the search view.
Fixes #390

Return to search when viewing search results

---

src/mpris.rs
src/queue.rs
src/spotify.rs

Currently when all tracks in the queue have been played, and the playback has stopped, the play/pause button does nothing.
This PR copies the behaviour from the desktop client, with the queue restarting from the top and starting to play again if play/pause is pressed.
It also fixes a bug where if adding a track after playback had stopped, play/pause did nothing but next track would advance and play the new track in the queue. Now when pressing play/pause it plays the next track in the queue as expected.

Restart queue if pressing play when stopped

---

src/spotify.rs

When trying to play an album with an unavailable track, for example https://open.spotify.com/album/3nG37CdJEbz1c7KrOOQn4Z, it would skip to the next available track but the status would be shown as stopped, the progress bar would be frozen but audio was still playing in the background, and the play/pause button would do nothing.
Handling the changed event which is described as "Same as started but in the case that the player already had a track loaded.", the same way as Started/Loading correctly updates the status bar with the right info.

Fix not handling changed event

---

src/mpris.rs

Currently FinishedTrack and Stopped both returned "Stopped" leading mpris to report stopped after every track and then playing again when the new track starts.
Not sure if I am allowed to not return a value when we don't have a valid PlaybackState value. The [docs](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:PlaybackStatussays ) for the PlaybackState states "When this property changes, the org.freedesktop.DBus.Properties.PropertiesChanged signal is emitted with the new value." 
but I'm not very knowledgeable with DBus. 
I've not encountered any weird behaviour using the same debugging technique described in #395.
Fixes #395

Don't handle FinishedTrack as Stopped

---

Cargo.toml
README.md

This adds simple debian-packaging with cargo-deb.
I have seen this on https://github.com/Spotifyd/spotifyd, but I like ncspot much more, so I added it to the Cargo.toml and updated the Readme.md how to build a debian-package.

Add simple debian-packaging with cargo-deb

---

src/mpris.rs

Make a small useful thing allows to set loop status (one track, one playlist or none of them) using the MPRIS.

LoopStatus is now editable from MPRIS

---

src/artist.rs
src/spotify.rs

This PR improves album loading in artist view in the following 2 points:
1. Show all the albums (currently at most 50 albums are shown in artist view.)
2. Reduce API requests by batching

Improve album loading in artist view

---

Cargo.lock
Cargo.toml
README.md
src/commands.rs
src/config.rs
src/main.rs
src/traits.rs
src/ui/cover.rs
src/ui/layout.rs
src/ui/mod.rs

I implemented this ages ago, including support for both W3M and Überzug. @hrkfdn I think at the time you mentioned that you thought this was beyond the scope of the project.
I have recently refactored this feature completely so I could finally update my local fork to keep up with the upstream (Great work since then btw). I have thrown out W3M support because that was a complete mess and required X11 packages and other unsavory things. It also required constant redrawing, while Überzug is much easier to work with.
This is an optional feature, so when compiling without it, the only change is the addition of an `on_leave` method for views. Without the additional complexity of W3M, it should be fairly maintenance-free, and it's a feature I can't live without anymore.

Implement cover drawing as optional feature

---

src/album.rs
src/artist.rs
src/library.rs
src/playlist.rs
src/spotify.rs
src/track.rs

Combines all .filter.map chains with a single call to .filter_map instead.
`.filter` yields if closure returns `true`, `.filter_map` yields if closure returns `Some()`

Refactor all .filter.map chains to .filter_map

---

src/library.rs
src/ui/contextmenu.rs
src/ui/playlists.rs
src/ui/queue.rs

Use .find() instead of for each loop to find playlist.
Just thought it made it clearer than before.
Saw that library had a function called .items() which only returned the playlists so I reused it in needs_download and renamed it to .playlists() since that is what it returns.

Refactor needs_download and rename library.items to better convey usage

---

src/config.rs

Serializing an empty `Vec<Playable>` causes serde to panic as described
in #485 This commit tells serde not to serialize `queue` if it is an
empty `Vec`.

Allow creation of default userstate.toml file

---

src/library.rs

Don't save track when album does as it's default behavior of Spotify's official app.

Saving album

---

src/ui/statusbar.rs

Shown percentage is sometimes lower than actual because float number is cast to u16 without rounding, so for example 4.99_f64 becomes 4_u16. It's seen for example when pressing "volup 5" when volume is at 0%. When you do that the bar displays 4%.

Add rounding to volume percentage display

---

README.md
src/commands.rs

Previously, Shift+o opened the menu for the currently playing item
while Shift+x copied a link to the currently selected item. Now Shift
operates on the currently playing item in both cases.
Fixes #516.

Make behavior of Shift modifier consistent

---

src/ui/statusbar.rs

This is a small follow-up to #511 that changes the status bar icon for the 'stopped' state to ▶ (to make it consistent with the 'paused' state).

Use ▶ icon in stopped state

---

src/spotify.rs

The normalisation threshold should be in ratio space, but the default value is specified in dB space, so using it as the default implicitly without passing it through the `db_to_ratio` function causes distortion and clipping when normalisation is enabled.
Fixes #522.
Ideally this would be done internally in `librespot`, so revert this is this logic is added there (see https://github.com/librespot-org/librespot/issues/745).

Explicitly set default normalisation threshold for librespot

---

src/ui/statusbar.rs

b42315d accidentally changed both of these to the glyph for play, this reverts them back to the correct glyphs.

Fix nerdfont pause/stop glyphs

---

Cargo.lock
Cargo.toml
README.md

This follows from https://github.com/hrkfdn/ncspot/issues/23#issuecomment-603955270
Closes #254 
The CD can be setup for Windows releases too, see here https://github.com/42wim/ncspot/blob/master/.github/workflows/cd.yml
Once a release has been made, I'll make a PR in the scoop repos so that ncspot can be installed directly via scoop (like brew).

Add Windows instructions

---

src/queue.rs
src/ui/cover.rs

First off, thanks for building such an awesome Spotify client. My poor desktop machine would chug with the official client but this one uses so much less memory and CPU time -- it's a world of difference.
This PR adds album cover images to the notification. (A small feature I've wanted :smiley: )

add album cover to notification

---

README.md
src/album.rs
src/artist.rs
src/command.rs
src/commands.rs
src/playlist.rs
src/track.rs
src/traits.rs
src/ui/contextmenu.rs
src/ui/listview.rs

This adds a command `similar selected|current` which enables searching for
track recommendations for playlists, albums as well as single tracks.

Add command to show recommendations.

---

src/command.rs
src/commands.rs
src/main.rs
src/ui/help.rs

This enables useful combinations of commands like `Space -> queue; move
down 1` using ';' as command separator. ';' can be escaped using ';;'.

Enable binding multiple commands to a key.

---

README.md

ncspot has been added to Scoop's Main bucket

Add scoop instruction for installation

---

src/mpris.rs

Fixes [#654](https://github.com/hrkfdn/ncspot/issues/654)

Fixed MPRIS OpenUri function not respecting ncspot's shuffle setting.

---

README.md

First of all thanks for this software, it's quickly become my main Spotify client!
This PR fixes up 2 broken markdown anchor links in the "Configuration" section

[Docs] Fix link to theming section in configuration table

---

Cargo.lock
Cargo.toml
README.md
src/command.rs

I changed the `seek` command to use [parse_duration](https://docs.rs/parse_duration/latest/parse_duration/), so now it accepts not only milliseconds as input but also more convenient units (mix and match capability included). I think this is a good quality-of-life improvement.

Improved `seek` command to allow more units

---

src/command.rs
src/commands.rs
src/main.rs
src/spotify.rs
src/spotify_url.rs
src/ui/listview.rs

- A failed command parse now returns more detailed error info, closes #597
- Added API:
- `pub enum command::CommandParseError`
- Changed API:
- `pub fn command::parse(&str) -> Option<Vec<Command>>` -> `pub fn command::parse(&str) -> Result<Vec<Command>, CommandParseError>`
- Breaking changes:
- Some commands previously allow bad args silently and perform some default action. These cases will now fail fast.
- Examples:
- `shuffle onn` (misspelled `on`) no longer toggles shuffle.
- `volup -10` (negative not allowed) no longer increases volume by 1%.
- `sort title desending` (misspelled `descending`) no longer sorts in ascending.
- Commands affected: `shuffle`, `repeat`, `save`, `volup`, `voldown`, `sort`
- Continuous spaces in commands are now interpreted as one
- Examples:
- `sort title …

More detailed error message in case of command parse error

---

src/command.rs

Just a minor fix on my code in #684

`seek` spits out correct error when used with no args

---

.github/workflows/cd.yml
.github/workflows/ci.yml
src/queue.rs
src/ui/cover.rs
src/utils.rs

This PR, in essence, just moves the functions `download` and `cache_path_for_url` from cover.rs to utils.rs. This is done so that the notification icon can be used on Windows. These functions were not doing doing anything Unix-specific, but since the `cover` feature is disabled on Windows, they couldn't be used before.
I have also enabled notifications and clipboard features for CI/CD on Windows. I have tested them in all scenarios, but please let me know if I missed anything.

Remove notifications' dependency on 'cover'

---

Cargo.lock
Cargo.toml

This project already uses "dbus" crate; bundling two dbus API implementations in the ncspot binary doesn't make much sense, it just increases the binary size.

Use notify-rust with dbus instead of zbus

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Gets rid of the dynamically linked PortAudio dependency

Use Rodio backend for macOS builds

---

src/queue.rs

Previously, cover images were downloaded and cached even when the corresponding feature flag was disabled; this adds a check to make sure that the cover image is actually used before trying to get and store it.

Only download cover image when flag enabled

---

Cargo.toml
misc/ncspot.desktop
src/queue.rs

- Added a `.desktop` file so that the user can launch `ncspot` straight from the launcher of their desktop environment
- Added the desktop entry hint to notification so ncspot's logo can be displayed inline with the notification
On KDE Plasma:
- Before
- After

Add desktop entry & notification icon hint

---

src/command.rs
src/commands.rs
src/queue.rs
src/sharing.rs
src/ui/contextmenu.rs
src/ui/cover.rs
src/ui/listview.rs
src/utils.rs

Most were just unused imports and lint warnings, but `sharing.rs` was erroring with `wayland_clipboard` feature enabled.

Fix some errors and warnings when enabling/disabling features

---

README.md
src/config.rs
src/model/playlist.rs
src/ui/library.rs

Adds an option to the `config.toml` that allows a user to disable the display of usernames in the main library tab and against playlists.
This also updates the README.md file to account for this additional config option. 
This implementation follows a similar pattern to configuring custom [library_tabs](https://github.com/hrkfdn/ncspot/blob/main/src/ui/library.rs#L25), and custom [track_format](https://github.com/hrkfdn/ncspot/blob/main/src/model/track.rs#L186)
Fixes #853

Add 'hide_display_names' config option

---

src/commands.rs
src/ui/contextmenu.rs

Hello, I noticed that there was no easy way of following/unfollowing artists unless their tracks were in your library already, so I added a new option to the context menu. Now when pressing on "Show artist", you will have the option to select if you want to view the artist page or if you want to follow/unfollow the artist.

Added possibility to Follow/Unfollow artists via the context menu

---

Cargo.toml

Cursive supports true color support (rather than just the 256 terminal colors), but not with all backends. ncspot's default does not appear to be one that supports true color.
ncspot already has a feature flag for termion, which does support true color, so I suggest making that Cursive backend the default.

Switch Cursive backend defualt to termion for true color support

---

README.md
src/config.rs
src/main.rs
src/queue.rs

Added notification customization, like `track_format` (in fact, using the same string parser for options like `%artist`).
Addresses #874
(I'm new to rust, sorry if there's some egregious misuse of the language!)

Add notification customization

---

README.md

This is just a small change to the README.
While attempting to remove the podcasts tab, I discovered that the playlists must be in all lowercase, contrary to what the README states.
The main change is at line 348
```
| `library_tabs`                  | Tabs to show in library screen                                 | Array of `"tracks"`, `"albums"`, `"artists"`, `"Playlists"`, `"podcasts"` | All tabs            |
```
The letter P is capitalized in playlists, which is wrong, .
Other modifications were done by auto formatting.

Changes to README capitalized in playlists

---

src/ui/layout.rs

Fix back button mouse left click

---

src/spotify.rs

When updating to librespot 0.4.0 in c41294c, the volume and audio path
parameters were specified in the wrong order.
This broke the `audio_cache = false` case, as well as caching files in the `volume/` folder rather than the `files/` folder.

Fix order of parameters to Cache::new

---

src/ui/listview.rs
src/ui/pagination.rs

This PR fixes the pagination but that prevented loading. I also added some documentation to some of the less obvious methods. There is still a bug present that causes the pagination message to appear at the bottom of the Browse tab, even when there isn't any more items. Help would be wanted with fixing that. I could also open another separate bug report for that if that's easier :slightly_smiling_face: .
fixes #938

Fixes a pagination bug that caused items to not load when scrolling with the mouse

---

src/commands.rs
src/ui/contextmenu.rs

PlayTrackMenu was used before the refactor of the contextmenus. I forgot to clean up the struct before making the commit since rustc didn't complain. Just cleaning up my mistakes ;)

Cleanup: Remove PlayTrackMenu

---

src/queue.rs
src/ui/cover.rs
src/ui/layout.rs

Like mentioned in the corresponding issue by ayushjaipuriyar, ncspot would crash when the queue was empty, shuffled, and played. This commit fixes that, together with some minor clippy fixes.
fixes #943

Fix: Crash on liked artist but no liked music

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
src/config.rs
src/main.rs
src/serialization.rs
src/ui/layout.rs

- Add manual implementation for panic that logs backtrace to a file.
- Remove all manual output to stdout.
- Fix new clippy warnings from Rust 1.65.

fix(backtrace): Fix backtrace logging and stdout

---

src/main.rs

It appears that calling `println!` after setting the cursive backend is causing the cursor on the new line to shift to the end position of the `Connecting to Spotify..` message. After exiting `ncspot`, the user prompt appears in this offset position. Calling `println!` before the backend instead keeps the cursor at the start of the new line.

main.rs: println before setting up cursive backend.

---

src/main.rs

Just a small PR because I forgot to add the PanicInfo to the backtrace when I wrote that panic handler. It makes the backtrace easier to read at a glance.
```
[...]
at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:165:17
30: main
31: <unknown>
32: __libc_start_main
33: _start
at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
panicked at 'explicit panic', src/main.rs:123:5
```

Add back PanicInfo to backtrace.

---

README.md

Hi,
As requested in https://github.com/hrkfdn/ncspot/issues/1019, I expanded the README a bit with an example on how to extract the currently playing info in your terminal. Sorry it took me so long. Is this along the lines of what you had in mind? Feel free to let me know if any changes are required.

Add info on extracting currently playing to README

---

src/config.rs
src/theme.rs

Hi, thanks for this awesome software.
With the color theme I'm using, opening the context menu for a track and tabbing to the "Close" button, it was hard to read the focused (but now inactive) selected item in the list. cursive defaults to using dark blue for the HighlightInactive PaletteStyle for such items in a SelectView, and it seems useful to allow users to override this.
I added a theme option "highlight_inactive_bg" which overrides the default HighlightInactive color from cursive.

theme config support for cursive's HighlightInactive

---

src/spotify_api.rs
src/ui/layout.rs
src/ui/search.rs

Fix clippy warnings.

---

src/model/episode.rs
src/model/playable.rs
src/model/track.rs
src/ui/statusbar.rs
src/utils.rs

This PR applies the same logic to durations as the native Spotify client:
0:00
0:01
0:23
0:20
1:00
10:02
1:00:00
1:01:01
...
It applies it to all the places where currently the old method was used (statusbar left and right, track durations, episode durations).
closes #1048

Switch from MM:SS to HH:MM:SS duration representation if needed.

---

src/queue.rs

I don't know why this check exists, because at least to my understanding the cover feature is only for drawing the covers in the terminal. 
I tested this and it displayed the covers in my notifications without needing the "cover" feature, at least i think the cover feature isn't automatically enabled when i compile it with `cargo build`. 
And i personally don't see a reason why covers shouldn't be displayed for everyone. I don't want to use the "cover" feature but having the cover in my notifications is a thing i want.

let everyone have covers in their notifications

---

README.md
src/command.rs
src/commands.rs

Hi, this pull request add a "disconnect" command, usefull when your connection change and you want to force closing the socket for reconnect

commands: Adding "disconnect" command to force socket shutdown

---

.github/workflows/cd.yml
.github/workflows/ci.yml
src/ui/cover.rs

- Update all the actions to the latest version since some of them were using deprecated stuff.
- Use a different Rust toolchain installation action because the previous one is no longer maintained and generated deprecated warnings. The new one is by dtolnay (the author of the syn, anyhow and cargo-expand) so it will probably be maintained for a while :slightly_smiling_face: 
- Fix the last clippy warning that occurred by enabling all features.
- Cache the build artifacts as long as the dependencies don't change.
- Build the project instead of just checking it (I'm not sure but I think just checking can miss errors under some circumstances. Some projects check, others build.). Building doesn't add much extra time when caching the `target` directory anyways.
I hope this is ok. This is only …

CI: add clippy and update toolchain install action.

---

src/commands.rs
src/queue.rs
src/ui/listview.rs
src/ui/queue.rs

This bugfix changes the way the `ListView` renders the content. It adds a way to add an explicit order of items to `ListView` in the same way as `Queue` has, and uses that for rendering. I just want to ask to quickly check this one to make sure it doesn't break other things (I don't think adding the order and using it only for rendering should have side effects, but I'm not 100% sure about it).
closes #465

Fix queueview shuffle order.

---

src/commands.rs
src/model/album.rs
src/model/artist.rs
src/model/category.rs
src/model/episode.rs
src/model/playable.rs
src/model/playlist.rs
src/model/show.rs
src/model/track.rs
src/queue.rs
src/traits.rs
src/ui/contextmenu.rs
src/ui/cover.rs
src/ui/listview.rs
src/ui/playlist.rs
src/ui/statusbar.rs

Some basic cleanup of function signatures that took ownership of their parameters, even though they didn't need ownership. Switching over the usage of `Arc` to a normal borrow has the added benefit of cleaning up the code a bit since now a reference can be given instead of having to clone the values. The other benefit is that a lot of clones aren't necessary anymore. It's not going to have noticable performance benefits, but it is still a good thing to have less clones all over the code.

Change unnecessary usage of Arc to borrow instead.

---

src/ui/contextmenu.rs

Autojump seems to take precedence over regular keys, which isn't the wanted behavior, especially when there are playlists in the list that contain some of the most common Vim keybindings. For example when there is a playlist called 'jazz', pressing `j` will jump to that playlist instead of going down.
This commit disables autojump for now. If search inside the add to playlist dialog would be a wanted feature, it could be implemented using the default Vim search button `/` which would work the same way as searching in other lists works right now.
closes #881

Disable autojump for add to playlist dialog.

---

Cargo.toml

Bookworm favours pipewire over pulseaudio, so the dependency to the package "pulseaudio" from my previous PR #405 has to be removed. It seemes, it was never really necessary anyway, because "$auto" already adds the correct dependency to "libpulse0".

Fix debian dependencies for Bookworm

---

.cargo/config.toml
.gitignore
Cargo.lock
Cargo.toml
README.md
src/lib.rs
src/main.rs
xtask/Cargo.toml
xtask/src/main.rs

This commit introduces semi-automatic manpage generation using the xtask workflow. This automates generation of manpages using the provided clap Command struct. I only wanted to suggest it for now, so I'm making it a draft.

Add manpage generation using xtask.

---

.gitignore
Cargo.lock
README.md
src/lib.rs
xtask/Cargo.toml
xtask/src/main.rs

This adds the option to automatically generate shell completion scripts for a variety of shells (currently bash, zsh, fish, elvish and powershell) using `cargo xtask generate-shell-completion`. It uses the crate `clap_complete` to automatically create these completions based on the `clap::Command` struct. It could be handy for package maintainers to add these scripts to their package.

Automatic shell completion generation using xtask.

---

src/ui/statusbar.rs

As of https://github.com/ryanoasis/nerd-fonts/issues/1096 nf-mdi* glyphs are marked obsolete in nerd-fonts upstream
Update the glyphs to non-deprecated nf-fa* counterparts
The current glphys used in ncspot are marked obsolete:
| play | pause | stop |
|--------|--------|--------|
| ![image](https://user-images.githubusercontent.com/302375/226118977-85b2d35b-951d-4a8f-8a8e-fef224003d55.png)  | ![image](https://user-images.githubusercontent.com/302375/226119033-2231e56e-649d-46af-ac4a-16886d285782.png) | ![image](https://user-images.githubusercontent.com/302375/226119044-b259b6df-fad6-4e71-af04-8289619a63dc.png) | 
> From https://www.nerdfonts.com/cheat-sheet
An added bonus to the update may be a bugfix too! There is an issue opened here: https://github.com/hrkfdn/ncspot/issues/824 which is …

statusbar: update nerdfont glyphs

---

doc/users.md

I noticed the docs for `library_tabs` didn't mention that `browse` is a valid option, but I'm able to use it in my config
```
library_tabs = ["playlists", "tracks", "browse"]
```

Add 'browse' to 'library_tabs' docs

---

src/ui/listview.rs

Change the behavior of `ListView` to treat a click on an item that is already selected as a double click. It allows the user to play songs (not episodes since currently it's not possible to determine if a `ListItem` is an episode) by "double clicking" them. It is a bit of a hack, but it works pretty well. A possible downside is that when people that don't like mouse integration in a TUI click to focus the terminal window, it could jump to the song they clicked if that happened to be the selected one.
closes #917

Emulate double click to play items.

---

src/ui/listview.rs

When removing an element, it is important to check whether it was the last element in the list and decrement the selected index if so.

fix(ui): ListView decrement selected on remove

---

src/queue.rs

Previously only the first notification (for each time the application launches) is actually sent on XDG (Linux) because the notification ID was reused incorrectly. This is a simple fix that removes the reuse.

Fix incorrect notification ID reuse on XDG

---

src/ipc.rs

For instance for when multiple ncspot instances are running. In that case the PID will be appended to the path, i.e. `~/.cache/ncspot/ncspot.20707.sock`.
Also ncspot will now delete the socket on shutdown.
Fixes #1158

Support multiple IPC sockets

---

src/application.rs
src/authentication.rs
src/command.rs
src/commands.rs
src/config.rs
src/lib.rs
src/library.rs
src/main.rs
src/mpris.rs
src/panic.rs
src/queue.rs
src/spotify.rs
src/spotify_api.rs
src/ui/cover.rs
src/ui/layout.rs
src/ui/mod.rs

Quite some Rust TUI applications move their 'global' data into a struct called `App` or `Application`. Other types of Rust (or non-Rust) applications might do this as well, I just checked TUI Rust applications. This makes it very clear what data belongs to the 'global' scope or in other words, to the application itself. For ncspot, this would be things like the queue, the library, the web API, probably the parsed configuration, Cursive and probably some other things. It makes the `main.rs` file more readable and less scary looking for new contributors, and gives a nice overview of what ncspot consists out of from looking at the `Application` struct definition.
Programs I checked were:
- zellij client
- spotify-tui
- wiki-tui
- gitui
- ox
- helix
- some others (I forgot)
I forgot which …

Refactor the entry point to make it more readable

---

src/ui/layout.rs

Don't index into the command line command as the prefix can be altered by the user and therefore be a multi-byte unicode character.

fix: command line multi-byte prefix panic

---

src/ui/layout.rs

When moving inside the command line, if the cursor is at either edge of the buffer, the events aren't consumed and propagated further into the view tree. This prevents that behavior.
fixes #1133

Prevent tab switching from the command line

---

README.md
doc/users.md

The Snapcraft package seems to have been removed. Therefore the links in the documentation should also be removed.

docs: remove Snapcraft installation source

---

doc/users.md

Since people were having problems when installing from crates.io, it would be nice to document it to prevent further problems.

docs: add `cargo` installation method

---

Cargo.toml

chore: improve release build options

---

src/ui/layout.rs

The `screenchange` member variable on `Layout` didn't seem to be used for anything except for debugging. A comment in `on_layout` makes it seem like it wasn't meant to be used for debugging purposes but for actual functionality that wasn't implemented.

refactor: remove unused `screenchange` variable

---

doc/users.md

The original project has seen very little activity since 2021 and was officially abandoned early this year. It would be a good idea to recommend an alternate implementation.
Also worth looking into is [libsixel](https://github.com/saitoha/libsixel), which is already supported by a good number of terminals ([source](https://www.arewesixelyet.com/)). But that can wait.

Update documentation: recommend Ueberzug++

---

src/library.rs

Ignore leading "The" when sorting albums and artists by artist name in the library.
e.g. "The Animals" now appears sorted under 'A' instead of under 'T' alongside other artists whose names begin with "The"

Sort Artists Ignoring "The"

---

src/model/playable.rs
src/model/playlist.rs
src/model/track.rs
src/spotify_api.rs
src/ui/listview.rs
src/ui/playlist.rs

As reported in #1231:
Local files in playlists have no IDs. When trying to delete them ncspot crashes as it tries to extract a track ID.

Fix: Gracefully handle local files

---

doc/users.md

This will fix the description of the default keybinding <kbd>Ctrl</kbd>+<kbd>s</kbd>
Links:
[1] https://github.com/hrkfdn/ncspot/blob/main/src/commands.rs#L430
[2] https://github.com/hrkfdn/ncspot/blob/main/src/ui/queue.rs#L166

docs: update users.md

---

src/command.rs
src/commands.rs
src/config.rs
src/events.rs
src/ext_traits.rs
src/ipc.rs
src/main.rs
src/model/category.rs
src/model/playable.rs
src/model/playlist.rs
src/model/track.rs
src/mpris.rs
src/queue.rs
src/spotify.rs
src/spotify_api.rs
src/spotify_url.rs
src/spotify_worker.rs
src/ui/help.rs
src/ui/layout.rs
src/ui/modal.rs
src/ui/pagination.rs
src/ui/queue.rs
src/ui/search.rs
src/ui/search_results.rs
src/ui/statusbar.rs

Clippy's `use_self` line ensures that `Self` is used instead of the real name whenever possible. This makes searching easier and cleans up the code a bit.
closes #1175

style(clippy): enforce clippy `use_self` lint

---

src/mpris.rs

Append `instance<pid>` to the MPRIS bus name to prevent two instances from fighting over the same bus name.

fix: prevent MPRIS D-Bus duplicate name

---

src/command.rs

Remove the placeholder entries from the command aliases.

chore: remove placeholder code

---

Cargo.lock
Cargo.toml
src/application.rs
src/command.rs
src/config.rs
src/main.rs
src/mpris.rs
src/spotify.rs
src/spotify_api.rs

The `lazy_static` crate was superseded by the `once_cell` crate which has been included in Rust's standard library since version `1.70`. Remove the `lazy_static` dependency and refactor all use cases to use `std::sync::OnceLock` instead.

refactor: remove `lazy_static` crate

---

Cargo.lock
Cargo.toml
src/application.rs

Instead of trying to handle signals for every step of the `cursive` event loop, move the signal handling into its own asynchronous task and send callbacks to `cursive` when a signal arrives.

feat: move to async POSIX signal handler

---

src/application.rs

Disable the useless trace logs from the `cursive_buffered_backend` crate.

fix: disable `cursive_buffered_backend` tracing

---

src/ipc.rs

Prevent a panic when the IPC socket isn't available when the user quits `ncspot`.

fix: prevent IPC socket cleanup panic

---

src/mpris.rs

This fixes a bug that would cause a panic when quiting the process normally. `tokio::select!()` was used to await a single branch, which is useless as it can be replaced by a normal await.
closes #1298

fix: MPRIS loop `tokio::select!()` panic on exit

---

.gitignore

The leading slash forces Git to only look for the mentioned files from the root of the directory, not inside allowed subdirectories.

fix: add leading slash to gitignore paths

---

CHANGELOG.md
README.md
doc/developers.md
doc/users.md
src/cli.rs
src/config.rs
src/lib.rs
src/main.rs
src/ui/help.rs
src/utils.rs

Adding an info command allows the documentation to refer to it when mentioning platform specific information. This gives users a nicer experience since they don't need to think about how `ncspot` will behave on their system, but can run `ncspot info` to get that information.
closes #1325

feat: add `info` command line subcommand

---

CHANGELOG.md
src/mpris.rs

This fixes a small inconsistency between the MPRIS implementation and the specification. The specification allows any number when setting the volume, which have to be clamped to the effectively allowed range in the application.
https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:Volume
- Instead of only changing the number if it is in the range 0.0..0.1, always set it after clamping it to that range.
\/

fix: allow any value to set MPRIS volume

---

CHANGELOG.md
src/mpris.rs

Currently, the MPRIS previous does nothing when the song is the first in the queue, when it should restart the song (as is the case if one uses the `previous` keyboard shortcut in the TUI).  This can fixed by making the MPRIS function `can_go_previous` identically true, rather than checking if there's a previous song in the queue.
One might consider this is somewhat related to #1110?

MPRIS: can_go_previous should always be true

---

CHANGELOG.md
src/application.rs

Instead of crashing on Termux, no IPC socket is created. This is a temporary solution until a suitable runtime directory for the Termux platform can be found.
- Make the IPC socket optional in case no suitable user runtime directory can be found on the platform.
#1345 

fix: crash on Termux due to missing runtime directory

---

src/main.rs
src/spotify_worker.rs

Found there were two inherent `impl`s for `Worker`, for which there is apparently a Clippy lint.

style: deny `clippy::multiple_inherent_impls` lint

---

src/spotify_api.rs
src/spotify_worker.rs

The channel does not need to be asynchronous as the receiving end is used in a blocking manner and the sending end of a regular channel never blocks.
- Remove the asynchronous futures `oneshot` channel in favor of a regular one

chore: remove unnecessary asynchronous channel

---

.github/workflows/update-rust-toolchain.yml
rust-toolchain.toml

Keeping the used toolchain version in version control makes sure that when building older versions, the same toolchain is used every time. For example, when `ncspot 0.12.0` has always been compiled with Rust version `1.67.0` but the currently installed version is `1.73.0`, this file would cause Rustup to download the older version again.

chore: keep track of used toolchain version

---

rust-toolchain.toml

Automatic change by the [update-rust-toolchain](https://github.com/a-kenji/update-rust-toolchain) Github Action.
Github Actions will not run workflows on pull requests which are opened by a GitHub Action.
For examples on how to run an workflows on this pr, please go to the [readme](https://github.com/a-kenji/update-rust-toolchain/blob/main/README.md#running-github-actions-on-the-action).

chore(toolchain): update

---

.github/workflows/update-rust-toolchain.yml

The latest version of the Rust toolchain update action supports a `pr-branch` input. It's not yet supported on `v1.1`.
- Remove the unsupported input from the action.

chore(actions): remove unsupported `pr-branch` input

---

Cargo.toml
src/main.rs
xtask/Cargo.toml
xtask/src/main.rs

Move the Rust and Clippy linting options into the Cargo manifest and share them with all the packages in the workspace. This ensures a consistent style in all packages.
- Move all the linting options into the Cargo manifest under a `workspace.lints` table
- Enable workspace lints in all packages
- Remove the previous Clippy lints from the `main.rs` in the `ncspot` package
- Fix `use_self` style issue in `xtask` package

style: share linting options across packages

---

src/library.rs
src/model/playlist.rs
src/model/track.rs
src/mpris.rs
src/spotify_api.rs
src/ui/contextmenu.rs
src/ui/playlist.rs
src/ui/playlists.rs
src/ui/queue.rs

Lots of small fixes to the APIs and functions in the `library` module, mostly following best practices outlined in the Rust library guidelines. Changes outside the `library` module were mostly required changes after changing function signatures.
- Function signature changes to make them more general (e.g. `&[T]` instead of `Vec<T>` when possible)
- Add documentation comments to most functions in the `library` module
- Remove a bunch of clones in favor of borrows when possible
- Change function signatures to accept mutable types directly instead of `Arc<RWLock<T>>` leaving locking up to the caller
- Restructure some function bodies to make their inner working clearer at first glance, but keeping their functionality the same
- Write serialized cache data directly to cache file instead of …

refactor(library): various Rust style optimizations

---

src/spotify_worker.rs

The purpose of the manual ui refresh task isn't immediately clear. It was explained in the commit message of the commit that introduced it.
Add a comment that explains the purpose of the `refresh_ui` task in the worker thread.

docs(worker): comment purpose of UI refresh task

---

src/commands.rs
src/config.rs
src/events.rs
src/library.rs
src/model/album.rs
src/model/artist.rs
src/model/playlist.rs
src/model/track.rs
src/mpris.rs
src/queue.rs
src/spotify.rs
src/spotify_api.rs
src/theme.rs
src/traits.rs
src/ui/artist.rs
src/ui/listview.rs
src/ui/search_results.rs
src/ui/tabbedview.rs

General improvements to documentation and code clarity.
- Add documentation comments to various items
- Change web API return types from bool/Option to Result
- Create helper functions with descriptive names instead of comments
- Remove redundant/confusing types
- Fix some documentation comments as instructed by `cargo doc`
- Rename variables to clear names

docs: small overall documentation improvements

---

src/commands.rs
src/config.rs
src/events.rs
src/ipc.rs
src/lib.rs
src/library.rs
src/mpris.rs
src/queue.rs
src/spotify.rs
src/spotify_api.rs
src/ui/playlist.rs
src/ui/search_results.rs

Some small general refactoring to improve code readability and adhere to Rust conventions.
- Remove `expect` in favor of `unwrap` when the `Result`'s error variant contains the info in the `expect` anyway (eg. when locking things). The line number/context are given by the backtrace.
- Remove over-specification of types (`&T` instead of `&RWReadLockGuard`)
- Put reused values into constants
- `try_from` instead of manual function
- Change `if let Some(()) = ...` to `if T.is_some()`

refactor: general small refactors to simplify code

---

CHANGELOG.md
src/application.rs
src/main.rs
src/spotify.rs

When the user has an error in their audio backend configuration or doesn't have audio backends available, gracefully exit instead of panicking.
Move audio backend initialization into the main thread for simpler error handling. Propagate errors up to the main function and log/print them there before quitting. This makes sure that everything that needs to be dropped is dropped automatically (e.g. not the case when manual exit from `Application::new()` which needs manual drop of `CursiveRunner` to reset terminal).
closes #1383 

fix: gracefully exit when misconfigured or unavailable audio backend

---

src/spotify.rs
src/spotify_api.rs
src/ui/search_results.rs

mpris runs inside `tokio::runtime.spawn`. At some point it hits `metadata_changed->WebApi::track->api_with_retry`, which gets 401 response and tries to update the token.
This goes into `update_token`, which at a certain point calls *blocking* `token_rx.recv()`. Tokio runtime is not happy about that, as it uses the same thread for the `run_loop` in the worker. That's why `tokio::select!` doesn't work, we're essentially deadlocking, so the worker never pick up `RequestToken` command and `update_token` block forever.
Here I'm changing `update_token` to wrap `recv` in `spawn_blocking`, which makes `update_token` return a `JoinHandle`, on which the caller has to await. This doesn't work nicely in case of mpris though, as it is not an async function, and I don't know how to make it async as it …

attempt to fix https://github.com/hrkfdn/ncspot/issues/1358

---

src/spotify.rs
src/spotify_api.rs
src/ui/search_results.rs

1. `None` from `update_token` should only mean "no update needed", should not be used for errors. We now panic when worker channel is not set
2. Callers should correctly handle `None` result
https://github.com/hrkfdn/ncspot/issues/1401

Fix for issues/1401

---

CHANGELOG.md
src/application.rs
src/commands.rs
src/mpris.rs
src/spotify.rs
src/ui/statusbar.rs

When the volume is changed from inside `ncspot`, also send a `PropertyChanged` signal.
- Send a DBus `PropertyChanged` signal every time the volume is changed inside `Spotify`
- Make the `update()` command on the `MprisManager` more general with different signals
closes #1328

fix(mpris): missing `PropertyChanged` signal for volume

---

CHANGELOG.md
src/spotify_api.rs

sometimes we get an `Err` from `token_rx.recv()`, shouldn't panic in such cases
didn't create an issue

fix a panic when token update fails

---

.github/workflows/cd.yml
.github/workflows/ci.yml
CHANGELOG.md

Thanks to contributors test coverage is becoming a thing, thus it makes sense to run tests in CI workflows.
Additionally, switch back to `cargo build` instead of `cargo check`, as the tests need compilation anyway.

ci: Run tests in CI

---

CHANGELOG.md
README.md
doc/users.md

The Snapcraft installation method was removed in the past as the package disappeared from Snapcraft. It seems to be back and maintained, so it should be back in the documentation.
- Mention the Snapcraft installation method in the documentation and add the badge
\/

docs: add Snapcraft installation source

---

CHANGELOG.md

Remove implementation details from the changelog as they are provided by the link in the version title for each release. Also rephrase some changes to make them more clear.
- Correctly add links at the bottom so the titles lead to the actual changes
- Rephrase some stuff to make it more clear to non-developers
- Remove implementation details (things a user wouldn't see in the program, documentation or the CLI for `ncspot`)
\/

docs: improve and simplify changelog

---

Cargo.toml
src/command.rs
src/theme.rs

Warn `enum_glob_use`. This mostly has to do with my own code.
The rationale behind this is best explained by [this video](https://youtu.be/8j_FbjiowvE?t=97).
No user facing changes.

Clippy: warn `enum_glob_use`

---

src/utils.rs

changed cfg!(linux) to cfg!(target_os = "linux") since the former is not actually valid, but produces no bug. this wasn't causing any problem that i know of, but if the code is in here it should probably do what it says, or be removed
no issue created, just saw a warning when installing from master (though this warning is not showing up again for some reason)

cfg fix for linux

---

CHANGELOG.md
src/spotify_url.rs

Fixed issue where localized strings weren't properly handled.
[#1455](https://github.com/hrkfdn/ncspot/issues/1455)

fix: support localized Spotify URLs

---

.editorconfig
.gitignore
.vscode/.gitignore
.vscode/extensions.json

As Visual Studio Code is the most popular editor at the moment, it makes sense to recommend the EditorConfig extension because it's not included by default. Also enable the final newline in files again as that was the default until the EditorConfig file was added.
- Add extension recommendation file for Visual Studio Code and recommend the EditorConfig extension
- Change the `insert_final_newline` option in the EditorConfig back to `true`
\/

style(vscode): add EditorConfig extension recommendation

---

CHANGELOG.md
doc/users.md

#1420 introduced the option `ac_port` to specify the port used by librespot.
This option works great, except when following the documentation and example only.
- The option is named `ap-port` in librespot.
- The option is named `ap_port` in [ConfigValues](https://github.com/hrkfdn/ncspot/blob/9624c03264bb4038138f03374c4bfb70db7bc850/src/config.rs#L105).
- However, the option is named `ac-port` in the documentation and in #1420, which doesn't work, as described below.
In ncspot/config.toml:
- ❌ `ap-port = 443` does nothing, librespot uses port 4070
- ✅ `ap_port = 443` librespot uses HTTPS
Rename `ap-port` option by `ap_port` in the documentation.
Should the changelog be updated too?
Changelog of 1.1.1 contains `ap-port`, which is misleading.

docs: Rename `ap-port` option as `ap_port`

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/application.rs
src/ext_traits.rs
src/ui/contextmenu.rs
src/ui/mod.rs

This updates cursive to 0.21.0. This release includes a buffered backend internally, so there is no need for a separate `cursive_buffered_backend` crate.
The main change is that `View` now require `Send + Sync`, so generic views should forward these requirements.
Note that the actual views here were already `Send + Sync`, and no logic change was needed.

Update cursive to 0.21.0

---

src/application.rs
src/mpris.rs
src/queue.rs
src/spotify.rs

My pr addresses some of the inconsistencies in ncspot's mpris
implementation. While the previous logic is technically good enough, it
is inflexible and reports redundant information.
I've tried to address those issues to make it easier for software, that processes mpris events in
some way, to accurately react to player updates.
- 'Metadata' and 'Playback' updates have been separated into their own
command
- Mpris commands are only emitted from within spotify.rs
- Some parts of the application creation logic has been
restructured to allow for mpris events to be emitted upon startup
- The initial song loading code has been moved from 'Queue::new'
into 'Application::new'.
This closes  #1514 
Edit: An example of software that requires strict MPRIS …

MPRIS: Restructuring and cleanup

---

CHANGELOG.md
src/mpris.rs
src/queue.rs
src/spotify.rs

NB I am new to Rust so may have made some horrible mistakes in here!
The Mpris2 spec includes a `Seeked` signal which should be fired when the track position changes in an unexpected way i.e. when the user seeks to a different part of the track.
This PR implements this signal on seek events and also when a new track begins. The latter is not strictly required but has been observed in other players (e.g. VLC).
Closes #1492

Add Seeked signal to Mpris interface

---

src/spotify_worker.rs

With librespot 0.5 the `PlayerEvent` behavior for track seeking seems to have changed slightly and there is now a dedicated event. This broke seeking in tracks.
With this change the dedicated event is processed and track position changes should be picked up again.

fix: Handle librespot `Seeked` events

---

.github/workflows/cd.yml

ci: Remove cross-compilation targs

---

CHANGELOG.md
src/ui/cover.rs

Something seems to have broken the return of the variables from the unsafe block, leading to division by zero.
By making the query variable mutable the return works. 
#1528

fix(cover): Add mut to fix incorrect get of windowsize in cover

---

CHANGELOG.md
doc/package_maintainers.md
xtask/src/main.rs

The main man page would point to man pages for subcommands, which weren't created automatically by the man page xtask.
- Use the new `clap_mangen::generate_to()` function to generate all man pages automatically
- Tweak some documentation to mention multiple man pages being generated
\/

fix: missing automatic man page generation for subcommands

---

CHANGELOG.md
src/authentication.rs
src/spotify_worker.rs

This reverts commit fa298f4f44a66d5039749f589185ab61fefbcbdf.
Fixes #1547

fix(auth): Switch back to Spotify client ID

---

doc/users.md
src/config.rs

With the OAuth2 flow being default now the logic to fetch login credentials via external programs (i.e. `pass`) has become obsolote.
This change removes documentation/config leftovers.

chore(auth): Remove credential program leftovers

---

CHANGELOG.md
doc/users.md
src/model/playable.rs

Added option to only show the first listed artist on a track.
With `%artists`:
With `%artist`:

add %artist formatting option to only show single artist name

---

CHANGELOG.md

As this is a breaking change, it should definitely be represented in the changelog, which is the primary source of information about any user-facing changes.
Add the removal of the password manager feature to the "Removed" section of the changelog.
Also update the wording for another item in the "Fixed" section to say exactly what was fixed.
\/
(I'll also create a separate PR to remove some remaining documentation about the password manager feature.)

docs: add missing password manager removal to changelog

---

README.md
doc/users.md

Remove remaining password manager documentation and add some notes about the new OAuth2 flow.
\/

docs: remove remaining password manager documentation

---

.github/workflows/cd.yml
.github/workflows/ci.yml
CHANGELOG.md

Extend checks and release binary output to use [newly released](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) Arm64 runners.
- #1555

feat(ci): Lint + Build for aarch64

---

src/queue.rs

There is an error in the comment of `append_next` function in `queue.rs`.
Didn't create an issue

Corrected incorrect comment

---

CHANGELOG.md
src/application.rs
src/model/playable.rs
src/model/track.rs
src/spotify.rs

- fix: Skip unplayable tracks
I think this worked before but must have regressed. The value `is_playable`
was not taken into account and instead overshadowed by a dummy method.
Fixes #1552
- chore: Tweak log levels a little
Use `Debug` level for all modules except `ncspot`, which shows `Trace` level 
logs by default.

fix: Skip unplayable tracks

---

CHANGELOG.md
src/ui/listview.rs
src/ui/queue.rs

In order to enable the queue view to play a title by clicking on the selected row, I did the following changes:
- Most of the `on_event`  logic moved into a separate public function in order to reuse the existing code as much as possible in the queue ui.
- This new `handle_mouse_event`  function either directly handles the incoming event or, in the case of the play option, returns a `Command` which then can be handled separately by different views. This in theory could enable more commands in the future if required.
[#1638](https://github.com/hrkfdn/ncspot/issues/1638)

Prevent Queue UI from freezing when clicking on a selected item
