src/events.rs, src/main.rs, src/ui/playlist.rs
Make loading the playlist asynchronous by not doing it `main.rs` and scheduling an event.
=> Load playlists only when opening the playlist screen

Cargo.toml
=> allow use of cursive/termion-backend

src/album.rs, src/artist.rs, src/config.rs, src/events.rs, src/main.rs, src/playlists.rs, src/queue.rs, src/spotify.rs, src/theme.rs, src/track.rs, src/traits.rs, src/ui/layout.rs, src/ui/listview.rs, src/ui/mod.rs, src/ui/search.rs, src/ui/statusbar.rs, src/ui/tabview.rs
=> Add TabView, allow searching for albums, artists, playlists

src/album.rs, src/artist.rs, src/commands.rs, src/library.rs, src/playlist.rs, src/spotify.rs, src/track.rs, src/traits.rs, src/ui/album.rs, src/ui/artist.rs, src/ui/layout.rs, src/ui/listview.rs, src/ui/mod.rs, src/ui/playlist.rs, src/ui/search.rs
Adds a view stack to `Layout` and commands for opening the selected item and going to the respective album/artist.
=> Implement browsing albums, artists and playlists

src/command.rs, src/commands.rs, src/config.rs, src/main.rs, src/queue.rs, src/traits.rs, src/ui/album.rs, src/ui/artist.rs, src/ui/layout.rs, src/ui/library.rs, src/ui/listview.rs, src/ui/playlist.rs, src/ui/playlists.rs, src/ui/queue.rs, src/ui/search.rs, src/ui/tabview.rs
Exploration of needed changes for #74.
Biggest needs right now is handling default command behavior and the command line - both are completely disabled at this time.
=> WIP: Move to enum-based commands

src/commands.rs
Hi!
Can we have emacs keybindings in navigation?
=> Add emacs navigation keybindings

src/mpris.rs
Fast forward and rewind support into `mpris.rs`. Desired addition for controlling ncspot from py3status.
=> Added additional dbus support

src/spotify.rs
Hey, this is actually just a fix to a "bug" that just spawned from me not properly testing my stuff. The volume set in the config file was not set properly on the initial start of the program. So this is literally just a one-liner.
=> Actually set volume when reading in from config

src/library.rs, src/playlist.rs, src/spotify.rs, src/ui/listview.rs, src/ui/playlist.rs
An attempt to fix #209 
Keep in mind I am extremely new to rust so please do not hesitate to correct me where I am making heinous mistakes! :)
So far I have it making the correct API request when you hit `d` on a track in a playlist, but it does not update the playlist view until you backspace out of the playlist and `o` back into it. Not sure what the disconnect there is.
=> enh: add methods and api usage to delete track from playlist

README.md
As described in: https://github.com/hrkfdn/ncspot/issues/212#issuecomment-652055797
=> Add comment to use `--locked`

README.md
See https://github.com/hrkfdn/ncspot/pull/214#issuecomment-653776631
=> Fix "workarround" typo for "workaround"

README.md, src/command.rs, src/commands.rs, src/config.rs, src/main.rs
=> implement command to reload config

src/mpris.rs
Implementation of Seek & SetPosition methods of MPRIS interface described here: https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html
=> Change track's position using MPRIS

src/album.rs, src/artist.rs, src/commands.rs, src/main.rs, src/mpris.rs, src/playlist.rs, src/spotify.rs, src/ui/contextmenu.rs, src/ui/help.rs, src/ui/modal.rs
e.g. to process vim-like keybindings for navigation
fixes #108, fixes #157, fixes #178, fixes #199, fixes #250
=> make contextmenu aware of commands

Cargo.lock, Cargo.toml, src/main.rs
character printing.
https://github.com/hrkfdn/ncspot/issues/221
Patch by rvp and kamil to fix character printing.
Fixes issue #221
=> Use libc for setlocale() to fix non-ASCII

src/library.rs, src/playlist.rs, src/ui/contextmenu.rs
=> Add dialog for adding duplicate tracks to a playlist

.gitignore, Cargo.lock, Cargo.toml, README.md, src/command.rs, src/commands.rs, src/library.rs, src/main.rs, src/mpris.rs, src/playlist.rs, src/ui/contextmenu.rs, src/ui/playlist.rs
Use the command `newplaylist <name>` to create a new playlist
Fixes #242
=> feat: create new empty playlist via command

src/mpris.rs
The MPRIS function to get volume was hardcoded to always return 100%; it now returns the actual volume. Also added MRIS function to set the volume. Both appear to be working on my device with playerctl.
resolves #315
=> fix mpris get volume; added mpris set volume

README.md
aebf475 changed it to PulseAudio.
=> Fix documentation of default backend

src/commands.rs, src/playlist.rs, src/ui/contextmenu.rs
=> Add hjkl controls for AddToPlaylistMenu

src/album.rs, src/playable.rs, src/track.rs, src/traits.rs, src/ui/contextmenu.rs, src/ui/listview.rs
Currently when using "show artist" or "goto artist" and multiple artists are present, only the first artist is shown. This PR adds a new select dialog where the user gets to select which artist to go to.
The dialog is only shown when multiple artists are present, otherwise it goes directly to the artist.
=> Add select artist dialog when multiple artists

Cargo.lock, Cargo.toml
=> Pin syn to 1.0.57

src/playlist.rs, src/ui/playlist.rs
Propagate deletion result from delete_tracks function and check it before removing track from listview.
=> Fix removing listview item even if not succesfully deleted

README.md
Had trouble ctrl+f'ing for the pause hotkey so thought it might be helpful to add that word to the Readme
=> Updated Readme to include pause

src/spotify.rs, src/track.rs, src/traits.rs, src/ui/contextmenu.rs
Recommentations -> Recommendations
=> Fix spelling mistake of recommendations

README.md
Thanks for the great project!
I tend to be a bit cagey about giving my username and password to random CLI scripts, and I wanted to make sure that my password was not persisted to disk. Glad to see that it isn't, so I figured I'd document (my take on) how it works.
=> Document authentication and stored credentials.

.github/workflows/cd.yml
=> Add Windows release builds

src/ui/statusbar.rs
Hey, really liking the project!
I missed being able to change volume by scrolling on the volume % display value.
I calculate the width of the volume display text and use the length of the string when checking for scroll mouse events.
Hope this is relevant :)
=> Change volume when scrolling on it

Cargo.lock, Cargo.toml, src/album.rs, src/artist.rs, src/episode.rs, src/library.rs, src/mpris.rs, src/playable.rs, src/playlist.rs, src/queue.rs, src/show.rs, src/spotify.rs, src/spotify_api.rs, src/track.rs, src/ui/artist.rs, src/ui/contextmenu.rs, src/ui/listview.rs, src/ui/playlist.rs, src/ui/search.rs, src/ui/search_results.rs
=> Update to rspotify 0.11.2

Cargo.lock, Cargo.toml, src/mpris.rs, src/sharing.rs
Hello, I added wayland clipboard support using the [wl_clipboard_rs](https://crates.io/crates/wl_clipboard_rs) crate.
Solves [#633](https://github.com/hrkfdn/ncspot/issues/633).
I tested with alacritty in both wayland and xorg and I also tested the primary clipboard and that seems to work as expected too.
=> Added Wayland clipboard support.

Cargo.lock, Cargo.toml, README.md, src/command.rs, src/commands.rs
=> Add `exec` command

src/spotify_api.rs, src/spotify_worker.rs
Hello
This pull request fixes a crash:
1. Start ncspot
2. Put the computer to sleep for an hour
3. Try to search for something
In this case the app crashed. The root cause of the crash is that the `response` in `get_token` holds a `MercuryError` instead of a result and the `unwrap` panics
With this fix the errors in the response processing are handled gracefully and the app doesn't crash.
The first search still fails after the sleep but the app doesn't crash
=> Remove panics in the update_token flow.

src/model/playlist.rs
Add secondary and tertiary sorting options to behave more like Spotify when sorting by artist or album.
=> Improve playlist sorting

Cargo.toml, README.md
I've rewritten some sections of README and made various minor edits to its other parts.
There's also a few comments in `Cargo.toml` explaining various features.
=> Improve documentation

src/model/album.rs, src/model/artist.rs, src/model/episode.rs, src/model/playlist.rs, src/model/show.rs, src/model/track.rs, src/traits.rs, src/ui/contextmenu.rs
I'm trying to improve the context menus for all the items, to make the context menu experience more consistent with what's already offered for tracks. This PR is related to #922 and isn't finished yet.
=> Improve context menus to make the UX/UI more consistent

Cargo.lock, Cargo.toml, src/main.rs
Save current state and close ncspot on `SIGTERM`
Fixes #948
=> Exit gracefully on `SIGTERM`

src/ui/layout.rs, src/ui/listview.rs, src/ui/pagination.rs, src/ui/search_results.rs
- Fixed a manual implementation of Clone on Pagination (needed extra trait bounds to be derivable)
- Made clippy happy :)
=> fix(todo): Fixed Clone impl marked todo on Pagination

src/queue.rs
Documentation isn't that necessary for programs, but I like to document while reading/understanding code, and it's so nice to have with the language server to quickly get some info about items, so thought I'd add it to upstream :)
=> Document queue module.

Cargo.lock, Cargo.toml
=> Use notify-rust with zbus instead of dbus and add ncurses_backend feature flag

src/model/album.rs, src/model/artist.rs, src/model/playable.rs, src/model/playlist.rs, src/model/show.rs, src/model/track.rs, src/ui/statusbar.rs
=> Update Nerdfont glyphs

src/command.rs, src/commands.rs
This touches upon #1198, but falls short of defining a key binding.
=> feat: add save current command

src/command.rs, src/commands.rs, src/ui/listview.rs
I added a command for adding the currently playing track or the currently selected track in a ListView to a playlist, since I wanted to map this to a shortcut.
=> Add command for adding song to playlist

src/model/album.rs, src/spotify_api.rs, src/ui/contextmenu.rs
Should speed up display of the context menu
Fixes #1225
=> Fix: fetch album only once

src/command.rs
This is a minor PR with very minor improvements.
=> Improve how we indicate that a command arg is optional

.github/workflows/cd.yml, Cargo.lock, Cargo.toml
- Is capable of 256 colors
- Can handle Shift+Up/Shift+Down/etc. (#1283)
=> Switch to Crossterm backend by default

src/model/track.rs, src/ui/listview.rs
If song is not available/playable, use secondary text color.
Fixes #1300
=> Change color of unavailable song

CHANGELOG.md, build.rs, src/lib.rs
=> Add Git commit hash to version string

README.md, doc/users.md
=> Add winget info

CHANGELOG.md, Cargo.lock, Cargo.toml, src/sharing.rs, src/ui/contextmenu.rs, src/ui/cover.rs, src/ui/listview.rs
Switch to `arboard` for clipboard access as it is still maintained
=> feat(sharing): Switch to `arboard` crate

CHANGELOG.md, Cargo.lock, Cargo.toml
=> chore: Bump version to 1.1.0

CHANGELOG.md, Cargo.lock, Cargo.toml, src/spotify_api.rs
=> Bump rspotify to 0.13.0

doc/users.md
Add some quotes around possible values for repeat to clarify they correspond to a string.
=> Add quotes around repeat values

src/library.rs
Remove a to-do and do some related cleanup.
- Remove a documentation to-do
- Do some related code cleanup
\/
=> chore: remove todo and improve some code in `src/library.rs`

rust-toolchain.toml
Add rust-analyzer to used components. Helps some editors (i.e. Emacs) with RLS setup.
=> chore: Add rust-analyzer to used components

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release preparation

CHANGELOG.md
Small fixes to `CHANGELOG.md` to make the links correct.
\/
=> docs: fix incorrect and broken links in `CHANGELOG.md`

rust-toolchain.toml
Automatic change by the [update-rust-toolchain](https://github.com/a-kenji/update-rust-toolchain) Github Action.
Github Actions will not run workflows on pull requests which are opened by a GitHub Action.
For examples on how to run an workflows on this pr, please go to the [readme](https://github.com/a-kenji/update-rust-toolchain/blob/main/README.md#running-github-actions-on-the-action).
=> chore(toolchain): update

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release prep

src/model/album.rs, src/model/playlist.rs, src/mpris.rs, src/queue.rs
=> chore: Linter fixes

shell.nix
=> feat(ci): Add nix-shell setup

src/queue.rs
Fixes the event loop starvation problem identified in #1631 by adding checks in the `Queue::next` method which determine whether there are any playable tracks remaining given the current queue contents and repeat settings. If there are no playable tracks left, playback is stopped, preventing the infinite loop which caused the application to stall. 
This issue was introduced in commit e3e75f7, which added skipping of unplayable tacks, but didn't account for the repeat mode edge cases. These changes maintain the skipping behaviour while accounting for those edge cases.
-  Add an invariant that  `queue::Queue`  items are playable. I initially implemented a solution enforcing this invariant at compile time using the newtype pattern in [this …
=> Prevent event loop starvation by unplayable tracks

CHANGELOG.md, src/ui/layout.rs
=> fix: Switch command line fg/bg colors

CHANGELOG.md, src/ui/statusbar.rs
=> fix: Do not crash due to unavailable tracks in queue

CHANGELOG.md, Cargo.lock, src/model/playable.rs, src/spotify_api.rs
=> fix: Playlist retrieval if list has podcasts
